### ISSUE TITLE
Build python versions with --with-pydebug flag / [Py_DEBUG]

### ISSUE THREAD

**Issue by simonsan** [actions/python-versions#16]
With the possibility to get Python builds from this Repositories Github Releases I wanted to propose to build these releases with [`--with-pydebug`](https://devguide.python.org/setup/#unix) flag (Explanation:  [[Py_DEBUG]](https://github.com/python/cpython/blob/master/Misc/SpecialBuilds.txt#L155))

Regarding these comments/PR:
https://github.com/actions/setup-python/pull/85
https://github.com/actions/virtual-environments/issues/786#issuecomment-620467793

**Comment by konradpabjan** [comment]
Hey @simonsan 

I'm going to close this issue here and we'll track the original request in: https://github.com/actions/setup-python/issues/86

We've decided to lock issue creation in this issue and we'll be tracking everything in `actions/setup-python` or `actions/virtual-environments` (easier to maintain and track python issues in 2 repos vs 3).

Sorry for the back and forth, this repo is pretty new and we're still working on deciding how we want to organize everything moving forward.

**Comment by simonsan** [comment]
Ok 👍
